### ISSUE TITLE
Number of items in timeline

### ISSUE THREAD

**Issue by prashmarathe** [RyanFitzgerald/vertical-timeline#1]
On my IE 11 the additional style is added after Item 5 (6th on wards) style=Opacity:0; which is making all items after 5th record as invisible. Do you have setting so we can set how many items needs to be visible ?

**Comment by RyanFitzgerald** [comment]
Hello,

I am having some difficulty reproducing your issue in IE11, would you be able to provide me with some steps to reproduce? 

All timeline elements should be visible regardless of how many items are created. The number of visible items will only ever change if animate is set to true (only items visible in the viewport will show and more will show as they enter the viewport). The one thing that I could think of is that potentially only 5 of your timeline elements are visible in the viewport currently, making the others invisible until they enter the viewport. Try setting animate: false for testing purposes and let me know if that fixes the issue in any way.

Regards,

Ryan

**Comment by prashmarathe** [comment]
You are right, once I set Animate: false the items are appearing correctly. in small screen it was fine as I was able to view only 3 items

Thanks for prompt response.
