### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by ergurdit** [RyanFitzgerald/vertical-timeline#2]
I am using you timeline jquery no doubt it works awesome but i am face a little bit issue in it when i am trying ShowDate = true this option is not work and couldn't find any html if required. So can you tell me how i will show date in it ?

**Comment by RyanFitzgerald** [comment]
I'm glad you like it!

To get the date to show up, its true that you need ShowDate = true, but you also need to add a data attribute of data-date = "some date here" to each div (timeline point) you want a date on. If there is no data attribute, it will simply not show anything for that div.

Let me know if that's still causing issues or if there is any confusion and I'll see what I can do!

**Comment by ergurdit** [comment]
Hi Ryan,

I need little bit more help from your side. Hope you will help me. I copied your html code can you send me html code with date attribute.

Regards.
Er.Gurdit singh

Contact Number
9878010408

Facebook
www.facebook.com/er.gurdit

Skype
er.gurdiiit
xyrin_gurdit

Date: Sat, 16 Apr 2016 12:44:54 -0700

**Comment by RyanFitzgerald** [comment]
Sure, here is the code you will need:

``` html
<div id="myTimeline">
    <div data-date="February 2016">
        My Content 1
    </div>
    <div data-date="March 2016">
        My Content 2
    </div>
    <div data-date="April 2016">
        My Content 3
    </div>
</div>
...
<script>
$('#myTimeline').timeline({
    showDate: true // Set to true by default
});
</script>
```

You'll notice that data-date is set on each of the timeline elements with a given date, as well as showDate is set to true.

Let me know if that helps.

**Comment by ergurdit** [comment]
<div id="timeline">                            <div>            <div data-date="February 2016">            <h1>Block 2</h1></div>        </div>            </div>    <script src="jquery.js"></script>    <script src="Responsive-Timeline-Generator-With-jQuery-Timeline/timeline.js"></script>    <script>        $('#timeline').timeline({            startSide: 'right',            alternate: false,            showDate: true,            animate: true        });
    </script>
I am using this code but it doesn't show date anywhere 
Regards.
Er.Gurdit singh
Contact Number
9878010408
Facebook
www.facebook.com/er.gurdit
Skype
er.gurdiiitxyrin_gurdit
Date: Sat, 16 Apr 2016 12:58:36 -0700

**Comment by RyanFitzgerald** [comment]
Hmm, have you linked to the stylesheet as well?

`
<link rel="stylesheet" type="text/css" href="path/to/timeline.css">
`

**Comment by ergurdit** [comment]
Yes everything working well. Just I have an issue to show date nothing else. That is why i was send my code to you.

Regards.
Er.Gurdit singh

Contact Number
9878010408

Facebook
www.facebook.com/er.gurdit

Skype
er.gurdiiit

Date: Sat, 16 Apr 2016 13:09:49 -0700

**Comment by RyanFitzgerald** [comment]
Looking back at your html, I think I've found the problem. The data attribute needs to be on the outermost wrapping div, as it is what is used to generate the timeline point.

So looking at your code, you have this currently:

``` html
<div id="timeline">                            
    <div>  <--- plugin builds date from parent div     
        <div data-date="February 2016">     
            <h1>Block 2</h1>      
        </div>            
    </div>
</div>
```

In order to fix that, just add the date to the parent div like so:

``` html
<div id="timeline">                            
    <div data-date="February 2016">  
        <div>     
            <h1>Block 2</h1> 
        </div>            
    </div>
</div>
```

Let me know if that makes sense and if it fixes the problem you are having.

**Comment by ergurdit** [comment]
Ya its working but it shows static date i want to take date automatically from system is it possible or not in this jquery ?
can you join me on skype if yes so please send me request on my official account xyrin_gurdit. Thanks for helping me Ryan.

Regards.
Er.Gurdit singh

Contact Number
9878010408

Facebook
www.facebook.com/er.gurdit

Skype
er.gurdiiit
xyrin_gurdit

Date: Sat, 16 Apr 2016 13:21:27 -0700

**Comment by RyanFitzgerald** [comment]
I'm not sure what languages you're planning on using, but you could output the date from a database or if you wanted the current system date, you could use the JavaScript Date object to get that as well.

I can't help with building the date dynamically since I don't know enough about what you're using, but if you wanted to simply output the current system time, you could do so like this:

``` javascript
$('#IDToYourDiv').attr('data-date', new Date(Date.now()))
```
