### ISSUE TITLE
Duplicated date tags

### ISSUE THREAD

**Issue by satfol** [RyanFitzgerald/vertical-timeline#3]
Hi Ryan and many thanks for your timeline, so well done that I want to use it on my online CV.
I am having an annoying issue with it though. I use it on 2 pages, with 2 different IDs, and the date tag gets duplicated on one of those 2 pages if I reduce the screen size to mobile.
If you have time to debug it, you can see it here http://mobile.chriswillox.com/#experience from a mobile device or just by reducing the size of your desktop window.
I have tried to remove jQuery mobile and other script I use on my page but they don't seem to interfere with yours. 
Running out of idea and really hope you could find what is causing this. Many thanks in advance.
Chris

**Comment by RyanFitzgerald** [comment]
Hey Chris,

Glad you like it and thanks for bringing this to my attention! It looks like the problem was with the way some referencing was done, so if you grab the updated JS the problem should be resolved.

Let me know how it goes,

Ryan

**Comment by satfol** [comment]
Hi Ryan,

Great fix!

**Comment by satfol** [comment]
It works perfectly.

May thanks,
Chris

**Comment by RyanFitzgerald** [comment]
Awesome, glad to hear!

Ryan
