### ISSUE TITLE
data-vtside Doesn't override

### ISSUE THREAD

**Issue by HiradRoshandel** [RyanFitzgerald/vertical-timeline#6]
Hi Ryan,

Great library! I'm trying to override the sides based on some condition in my code as you declared in your docs data-vtside="right" or data-vtside="left" but nothing happens and it just alternates by default.

**Comment by RyanFitzgerald** [comment]
Thank you! I've pushed a small change to address that bug and tested it, everything seems to be working. Let me know if you're still running into problems and I'll dig deeper. Sorry about that.
